import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { INTER_BOLD_BASE64, INTER_REGULAR_BASE64 } from "./fontData";

export interface ReportPdfInput {
  title: string;
  subtitle?: string;
  headers: string[];
  rows: Array<Array<string | number>>;
  /** Optional "key: value" lines rendered above the table. */
  summary?: Array<{ label: string; value: string }>;
}

function money(value: number): string {
  return `₹${value.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

/** Renders a branded A4 report (tables with ₹ support) and triggers a download. */
export function downloadReportPdf(input: ReportPdfInput): void {
  const doc = new jsPDF({ unit: "mm", format: "a4", compress: true });
  doc.addFileToVFS("BillFlow-Regular.ttf", INTER_REGULAR_BASE64);
  doc.addFont("BillFlow-Regular.ttf", "BillFlow", "normal");
  doc.addFileToVFS("BillFlow-Bold.ttf", INTER_BOLD_BASE64);
  doc.addFont("BillFlow-Bold.ttf", "BillFlow", "bold");

  const margin = 12;
  const width = doc.internal.pageSize.getWidth();

  doc.setFillColor(13, 148, 136);
  doc.rect(0, 0, width, 18, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("BillFlow", "bold");
  doc.setFontSize(14);
  doc.text("BillFlow", margin, 8);
  doc.setFontSize(15);
  doc.text(input.title, margin, 14);

  let y = 24;
  doc.setTextColor(17, 24, 39);
  if (input.subtitle) {
    doc.setFont("BillFlow", "normal");
    doc.setFontSize(9);
    doc.text(input.subtitle, margin, y);
    y += 5;
  }

  if (input.summary && input.summary.length > 0) {
    doc.setFont("BillFlow", "normal");
    doc.setFontSize(9);
    input.summary.forEach((line) => {
      doc.setFont("BillFlow", "bold");
      doc.text(`${line.label}:`, margin, y);
      doc.setFont("BillFlow", "normal");
      doc.text(line.value, margin + 45, y);
      y += 5;
    });
    y += 2;
  }

  autoTable(doc, {
    startY: y,
    head: [input.headers],
    body: input.rows.map((row) => row.map((cell) => String(cell))),
    margin: { left: margin, right: margin },
    styles: {
      font: "BillFlow",
      fontSize: 8,
      cellPadding: 2,
      textColor: [30, 41, 59],
      lineColor: [226, 232, 240],
      lineWidth: 0.1,
    },
    headStyles: { fillColor: [13, 148, 136], textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    didDrawPage: (data) => {
      const pageCount = doc.getNumberOfPages();
      doc.setFont("BillFlow", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(120, 130, 145);
      doc.text(
        `Generated by BillFlow · page ${data.pageNumber} of ${pageCount}`,
        width - margin,
        doc.internal.pageSize.getHeight() - 6,
        { align: "right" },
      );
    },
  });

  const filename = `${input.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${new Date()
    .toISOString()
    .slice(0, 10)}.pdf`;
  doc.save(filename);
}

export { money as formatPdfMoney };
