import { useEffect, useState } from "react";
import { Outlet, useLocation } from "react-router-dom";
import { X } from "lucide-react";
import { Topbar } from "./Topbar";
import { BrandMark, SidebarNav } from "./SidebarNav";
import { cn } from "@/lib/utils";

export function AppShell() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const location = useLocation();

  useEffect(() => {
    setMobileOpen(false);
  }, [location.pathname]);

  return (
    <div className="flex min-h-screen bg-muted/30">
      {/* desktop sidebar */}
      <aside className="sticky top-0 hidden h-screen w-64 shrink-0 flex-col border-r bg-white lg:flex print:hidden">
        <div className="flex h-16 items-center border-b px-5">
          <LinkHome />
        </div>
        <SidebarNav />
        <div className="border-t px-5 py-4 text-[11px] leading-relaxed text-muted-foreground">
          GST summaries generated by BillFlow are business reporting tools. They are not government
          filings unless produced through an authorised filing system.
        </div>
      </aside>

      {/* mobile sidebar */}
      {mobileOpen && (
        <div className="fixed inset-0 z-50 lg:hidden print:hidden">
          <div
            className="absolute inset-0 bg-black/50"
            onClick={() => setMobileOpen(false)}
            aria-hidden
          />
          <aside className={cn("absolute left-0 top-0 flex h-full w-72 flex-col bg-white shadow-2xl")}>
            <div className="flex h-16 items-center justify-between border-b px-5">
              <BrandMark />
              <button
                type="button"
                onClick={() => setMobileOpen(false)}
                aria-label="Close navigation"
                className="rounded-md p-1.5 hover:bg-accent"
              >
                <X className="h-5 w-5" />
              </button>
            </div>
            <SidebarNav onNavigate={() => setMobileOpen(false)} />
          </aside>
        </div>
      )}

      <div className="flex min-w-0 flex-1 flex-col">
        <Topbar onOpenMobile={() => setMobileOpen(true)} />
        <main className="mx-auto w-full max-w-[1400px] flex-1 px-4 py-6 sm:px-6">
          <Outlet />
        </main>
        <footer className="border-t bg-white px-4 py-3 text-center text-[11px] text-muted-foreground sm:px-6 print:hidden">
          BillFlow · GST Billing &amp; Invoice Management
        </footer>
      </div>
    </div>
  );
}

function LinkHome() {
  return <BrandMark />;
}
