"""Regenerates src/lib/pdf/fontData.ts (base64 TTF subsets used by jsPDF).

The PDF generator embeds these fonts so the Indian Rupee sign (U+20B9) and all
Latin characters render correctly in generated invoices.

Usage:  python scripts/embed_fonts.py
"""
import base64
import io
import os
import subprocess
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "lib", "pdf", "fontData.ts")
TMP = os.path.join(ROOT, ".fonttmp")

FONTS = {
    "INTER_REGULAR_BASE64": "https://cdn.jsdelivr.net/npm/@expo-google-fonts/inter/Inter_400Regular.ttf",
    "INTER_BOLD_BASE64": "https://cdn.jsdelivr.net/npm/@expo-google-fonts/inter/Inter_700Bold.ttf",
}

UNICODES = (
    "U+0020-007E,U+00A0,U+00B7,U+2013,U+2014,U+2018-201D,U+2022,U+20B9,U+2070,"
    "U+00B0,U+00BD,U+00BC,U+2122,U+00A9,U+00AE"
)


def download(url: str) -> bytes:
    print("downloading", url)
    with urllib.request.urlopen(url, timeout=60) as resp:
        return resp.read()


def subset(data: bytes, name: str) -> bytes:
    os.makedirs(TMP, exist_ok=True)
    src = os.path.join(TMP, name + ".ttf")
    dst = os.path.join(TMP, name + ".subset.ttf")
    with open(src, "wb") as fh:
        fh.write(data)
    cmd = [
        sys.executable, "-m", "fontTools.subset", src,
        "--unicodes=" + UNICODES,
        "--layout-features=",
        "--no-hinting",
        "--drop-tables+=DSIG",
        "--output-file=" + dst,
    ]
    subprocess.run(cmd, check=True, capture_output=True)
    with open(dst, "rb") as fh:
        return fh.read()


def main() -> None:
    try:
        import fontTools  # noqa: F401
    except ImportError:
        subprocess.run([sys.executable, "-m", "pip", "install", "--quiet", "fonttools"], check=True)

    parts = [
        "// AUTO-GENERATED by scripts/embed_fonts.py - do not edit by hand.",
        "// Latin subset of Inter (SIL Open Font License) including U+20B9 (Indian Rupee).",
        "",
    ]
    for const, url in FONTS.items():
        raw = subset(download(url), const)
        b64 = base64.b64encode(raw).decode("ascii")
        print(const, len(raw), "bytes ->", len(b64), "base64 chars")
        parts.append(f'export const {const} = "{b64}";')
        parts.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(parts))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
